### ISSUE TITLE
Write to Excel file only once

### ISSUE THREAD

**Issue by Bartleby2718** [Bartleby2718/ScrapeFundaWebsite#12]
Was working on #6 but couldn't get it working with `multiprocessing`. I guess I'll have to refactor first.

Reason 1. `multiprocessing` module requires that all objects be picklable, but some objects in `xlsxwriter` are not.
- Error I got:
> `_pickle.PicklingError: Can't pickle <class 'xlsxwriter.worksheet.String'>: attribute lookup String on xlsxwriter.worksheet failed`
- Related SO Question: https://stackoverflow.com/questions/8804830/python-multiprocessing-picklingerror-cant-pickle-type-function
  - Tried `pathos` in the second answer, but can't get it working.
  - I'd rather get used to the standard library first.

Reason 2. @gongdo's comment:
> 엑셀 라이브러리 안정성이 얼마나 좋은지 모르겠지만 보통은 그냥 plain text로 csv 형식으로 산출물을 모으고 엑셀로는 한번에 쓰는게 중간에 피눈물 날 일을 방지할 수 있어요.

So I'm gonna refactor the code first and then try `multiprocessing` again.

**Comment by gongdo** [comment]
...그런데 이 정도로 복잡한 코딩 스킬을 필요로한다면 리팩터링을 한다고 해서 유지보수, 가독성이 나아질리는 만무할 것 같네요.
만약 파이썬이 멀티 프로세싱에 대한 범용적이고 일반적인 해결 방법이 없다면 - 예를 들어 picklable이 뭔지 모르겠지만 이게 지원되고 안되고에 따라 특정 멀티프로세싱 도구를 쓸 수 없다면, 언어에 기대는 것 보다는 그냥 각 기능을 단일 입출력 프로세스(실행파일)로 만들고 메인 루틴에서는 각 기능을 병렬로 실행한 후 출력물을 수집하는게 훨씬 단순하고 유지보수도 편할 수 있겠단 생각이 드네요.

**Comment by Bartleby2718** [comment]
@gongdo 오랫동안 미루긴 했지만 복잡하진 않았어요. 말씀하신 대로 scrape한 결과를 리스트에 저장해 뒀다가(이 부분은 #6 에서 multiprocessing 이용해서 15초에서 4초로 단축) 한 번에 엑셀 파일로 썼습니다. (엑셀 관련된 부분은 62ms 걸리더라고요.)
참고로 picklable=serializable입니당 [pickle](https://docs.python.org/3/library/pickle.html)은 Python Standard Library에서 serialization/deserialization을 담당하는 라이브러리 이름이에요.
